spring:
  application:
    name: Bankersi2k24
  thymeleaf:
    check-template-location: true
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/bank-main
    username: bankerss
    password: bankersi2k24!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
